apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: work-rate-calculator
  namespace: production
  annotations:
    kubernetes.io/ingress.class: traefik-public
spec:
  entryPoints:
    - web

  routes:
    - match: Host(`work-rate-calculator.flowerhead.dev`)
      kind: Rule
      services:
        - name: work-rate-calculator
          port: 80
